export enum ErrorCodes {
  REQUIRED_FIELD = 'REQUIRED_FIELD',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_FIELD = 'INVALID_FIELD',

  INVALID_PRODUCT_PRICE_MIN_VALUE = 'INVALID_PRODUCT_PRICE_MIN_VALUE',
  INVALID_PRODUCT_PRICE_MAX_VALUE = 'INVALID_PRODUCT_PRICE_MAX_VALUE',

  // Login
  EMPTY_LOGIN = 'EMPTY_LOGIN',
  INVALID_LOGIN = 'INVALID_LOGIN',
  INVALID_LOGIN_MIN_LENGTH = 'INVALID_LOGIN_MIN_LENGTH',
  INVALID_LOGIN_MAX_LENGTH = 'INVALID_LOGIN_MAX_LENGTH',
  LOGIN_EXISTS = 'LOGIN_EXISTS',

  // Password
  EMPTY_PASSWORD = 'EMPTY_PASSWORD',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_OLD_PASSWORD = 'INVALID_OLD_PASSWORD',
  INVALID_PASSWORD_MIN_LENGTH = 'INVALID_PASSWORD_MIN_LENGTH',
  PASSWORD_REPEAT_MISMATCH = 'PASSWORD_REPEAT_MISMATCH',

  // Email
  EMPTY_EMAIL = 'EMPTY_EMAIL',
  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_EXISTS = 'EMAIL_EXISTS',

  // Captcha
  EMPTY_CAPTCHA = 'EMPTY_CAPTCHA',
  INVALID_CAPTCHA = 'INVALID_CAPTCHA',

  // Others
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_CODE = 'INVALID_CODE',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERNAME_EMPTY = 'USERNAME_EMPTY',
  NOT_ENOUGH_MONEY = 'NOT_ENOUGH_MONEY',
  WITHDRAW_TEMPORALY_UNAVAILABLE = 'WITHDRAW_TEMPORALY_UNAVAILABLE',

  // Product
  INVALID_PRODUCT_TITLE_MIN_LENGTH = 'INVALID_PRODUCT_TITLE_MIN_LENGTH',
  INVALID_PRODUCT_DESCRIPTION_MIN_LENGTH = 'INVALID_PRODUCT_DESCRIPTION_MIN_LENGTH',
  INVALID_PRODUCT_TITLE_MAX_LENGTH = 'INVALID_PRODUCT_TITLE_MAX_LENGTH',
  INVALID_PRODUCT_DESCRIPTION_MAX_LENGTH = 'INVALID_PRODUCT_DESCRIPTION_MAX_LENGTH',
  INVALID_PRODUCT_PRICE = 'INVALID_PRODUCT_PRICE',

  // Promo
  PROMO_EMPTY = 'PROMO_EMPTY',
  PROMO_NOT_FOUND = 'PROMO_NOT_FOUND',
  PROMO_ALREADY_USED = 'PROMO_ALREADY_USED',

  // Server
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  ACCESS_DENIED = 'ACCESS_DENIED',
  TO_MANY_REQUESTS = 'TO_MANY_REQUESTS',
  INVALID_RESPONSE = 'INVALID_RESPONSE'
}
